name: Build MarketStub APK

on:
  push:
    paths:
      - 'settings.gradle'
      - 'build.gradle'
      - 'gradle/**'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scaffolded repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle 8.6
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.6'

      - name: Generate Gradle wrapper
        run: gradle wrapper

      - name: Make wrapper executable
        run: chmod +x ./gradlew

      - name: Assemble Release APK
        run: ./gradlew clean app:assembleRelease --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MarketStub-${{ github.run_number }}.apk
          path: app/build/outputs/apk/release/app-release.apk
