name: Build MarketStub APK

on:
  push:
    paths:
      - 'settings.gradle'
      - 'build.gradle'
      - 'gradle/**'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout scaffolded project
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3) Install system Gradle (to bootstrap wrapper)
      - name: Install Gradle CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 4) Generate the Gradle wrapper
      - name: Generate Gradle wrapper
        run: gradle wrapper

      # 5) Make wrapper executable
      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # 6) Build Release APK
      - name: Assemble Release APK
        run: ./gradlew clean app:assembleRelease --no-daemon

      # 7) Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MarketStub-${{ github.run_number }}.apk
          path: app/build/outputs/apk/release/app-release.apk
