name: Generate & Build MarketStub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the (empty) repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java 17 + cache Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3. Install system Gradle (needed to generate wrapper)
      - name: Install Gradle CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 4. Scaffold the Android stub project
      - name: Scaffold MarketStub project
        run: |
          set -e
          # create module & wrapper dirs
          mkdir -p app/src/main/java/com/yourcompany/marketstub
          mkdir -p gradle/wrapper

          ## settings.gradle with pluginManagement
          cat > settings.gradle << 'EOF'
          pluginManagement {
            repositories {
              gradlePluginPortal()
              google()
              mavenCentral()
            }
          }
          rootProject.name = "MarketStub"
          include(":app")
          EOF

          ## root build.gradle declares the AGP plugin and wrapper task
          cat > build.gradle << 'EOF'
          plugins {
            id "com.android.application" version "8.2.0" apply false
          }
          
          subprojects {
            repositories {
              google()
              mavenCentral()
            }
          }
          
          task wrapper(type: Wrapper) {
            gradleVersion = "8.4"
          }
          EOF

          ## wrapper properties (v8.4)
          cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
          EOF

          ## app module build.gradle
          cat > app/build.gradle << 'EOF'
          apply plugin: 'com.android.application'

          android {
            compileSdk = 35
            defaultConfig {
              applicationId = "com.yourcompany.marketstub"
              minSdk = 21
              targetSdk = 35
              versionCode = 1
              versionName = "1.0"
            }
            buildTypes {
              release {
                minifyEnabled false
              }
            }
          }

          dependencies {
            // no external deps
          }
          EOF

          ## AndroidManifest.xml
          cat > app/src/main/AndroidManifest.xml << 'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.yourcompany.marketstub">

            <application android:label="Market Stub">
              <activity android:name=".MarketStubActivity"
                        android:exported="true">
                <intent-filter>
                  <action android:name="android.intent.action.VIEW"/>
                  <category android:name="android.intent.category.DEFAULT"/>
                  <category android:name="android.intent.category.BROWSABLE"/>
                  <data android:scheme="market"/>
                </intent-filter>
              </activity>
            </application>
          </manifest>
          EOF

          ## Java source
          cat > app/src/main/java/com/yourcompany/marketstub/MarketStubActivity.java << 'EOF'
          package com.yourcompany.marketstub;

          import android.app.Activity;
          import android.content.Intent;
          import android.net.Uri;
          import android.os.Bundle;

          public class MarketStubActivity extends Activity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
              super.onCreate(savedInstanceState);
              Uri uri = getIntent().getData();
              if (uri != null) {
                Intent i = new Intent(Intent.ACTION_VIEW, uri);
                i.setPackage("com.android.vending");
                i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(i);
              }
              finish();
            }
          }
          EOF

      # 5. Generate the Gradle wrapper scripts + jar
      - name: Generate Gradle wrapper
        run: gradle wrapper

      # 6. Make the wrapper executable
      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # 7. Clean & build the Release APK
      - name: Assemble Release APK
        run: ./gradlew clean app:assembleRelease --no-daemon

      # 8. Upload the resulting APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MarketStub-${{ github.run_number }}.apk
          path: app/build/outputs/apk/release/app-release.apk
