name: Generate & Build MarketStub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout (empty) repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install JDK 17 and cache Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3) Install Gradle CLI (for wrapper generation)
      - name: Install Gradle CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 4) Scaffold the Android stub project entirely in the workspace
      - name: Scaffold MarketStub project
        run: |
          set -e

          # Create folders
          mkdir -p app/src/main/java/com/yourcompany/marketstub
          mkdir -p gradle/wrapper

          # Root settings.gradle
          cat > settings.gradle << 'EOF'
          rootProject.name = "MarketStub"
          include ":app"
          EOF

          # Root build.gradle (defines wrapper task)
          cat > build.gradle << 'EOF'
          plugins {
            id 'com.android.application' version '8.1.0' apply false
          }
          task wrapper(type: Wrapper) {
            gradleVersion = '8.2'
          }
          EOF

          # Gradle wrapper properties
          cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          distributionUrl=https://services.gradle.org/distributions/gradle-8.2-bin.zip
          EOF

          # App module build.gradle
          cat > app/build.gradle << 'EOF'
          apply plugin: 'com.android.application'

          android {
            compileSdk = 35
            defaultConfig {
              applicationId = "com.yourcompany.marketstub"
              minSdk = 21
              targetSdk = 35
              versionCode = 1
              versionName = "1.0"
            }
            buildTypes {
              release {
                minifyEnabled false
              }
            }
          }

          dependencies {
            // no external dependencies
          }
          EOF

          # AndroidManifest.xml
          cat > app/src/main/AndroidManifest.xml << 'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.yourcompany.marketstub">

            <application android:label="Market Stub">
              <activity android:name=".MarketStubActivity"
                        android:exported="true">
                <intent-filter>
                  <action android:name="android.intent.action.VIEW"/>
                  <category android:name="android.intent.category.DEFAULT"/>
                  <category android:name="android.intent.category.BROWSABLE"/>
                  <data android:scheme="market"/>
                </intent-filter>
              </activity>
            </application>
          </manifest>
          EOF

          # MarketStubActivity.java
          cat > app/src/main/java/com/yourcompany/marketstub/MarketStubActivity.java << 'EOF'
          package com.yourcompany.marketstub;

          import android.app.Activity;
          import android.content.Intent;
          import android.net.Uri;
          import android.os.Bundle;

          public class MarketStubActivity extends Activity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
              super.onCreate(savedInstanceState);
              Uri uri = getIntent().getData();
              if (uri != null) {
                Intent i = new Intent(Intent.ACTION_VIEW, uri);
                i.setPackage("com.android.vending");
                i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(i);
              }
              finish();
            }
          }
          EOF

      # 5) Generate the Gradle wrapper (scripts + jar)
      - name: Generate Gradle wrapper
        run: gradle wrapper

      # 6) Make the Gradle wrapper executable
      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # 7) Build the Release APK
      - name: Assemble Release APK
        run: ./gradlew clean app:assembleRelease --no-daemon

      # 8) Upload the built APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MarketStub-${{ github.run_number }}.apk
          path: app/build/outputs/apk/release/app-release.apk
